name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: check
        run: sbt -v +scalafmtSbtCheck 
      - name: compile
        run: sbt -v compile
      - name: test
        run: sbt -v test
