name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
      - name: check
        run: sbt scalafmtSbtCheck scalafmtCheckAll
      - name: compile
        run: sbt compile
      - name: test
        run: sbt test